from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name='BlogPost',fields=[('id',models.BigAutoField(primary_key=True,serialize=False)),('title',models.CharField(max_length=180)),('slug',models.SlugField(unique=True)),('category',models.CharField(default='Automation',max_length=80)),('excerpt',models.TextField()),('body',models.TextField()),('published',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True))]),
      migrations.CreateModel(name='CaseStudy',fields=[('id',models.BigAutoField(primary_key=True,serialize=False)),('title',models.CharField(max_length=180)),('slug',models.SlugField(unique=True)),('category',models.CharField(max_length=100)),('summary',models.TextField()),('challenge',models.TextField(blank=True)),('solution',models.TextField(blank=True)),('workflow',models.CharField(blank=True,max_length=300)),('tech_stack',models.CharField(blank=True,max_length=300)),('image',models.ImageField(blank=True,null=True,upload_to='case_studies/')),('confidential',models.BooleanField(default=False)),('published',models.BooleanField(default=True)),('created_at',models.DateTimeField(auto_now_add=True))]),
      migrations.CreateModel(name='Lead',fields=[('id',models.BigAutoField(primary_key=True,serialize=False)),('kind',models.CharField(choices=[('contact','Contact'),('quote','Quote'),('audit','Automation Audit'),('booking','Consultation')],default='contact',max_length=20)),('reference',models.CharField(blank=True,max_length=24,null=True,unique=True)),('name',models.CharField(max_length=120)),('email',models.EmailField(max_length=254)),('phone',models.CharField(blank=True,max_length=40)),('company',models.CharField(blank=True,max_length=150)),('country',models.CharField(blank=True,max_length=80)),('service',models.CharField(blank=True,max_length=150)),('budget',models.CharField(blank=True,max_length=80)),('timeline',models.CharField(blank=True,max_length=80)),('tools',models.CharField(blank=True,max_length=250)),('source',models.CharField(blank=True,max_length=120)),('message',models.TextField()),('attachment',models.FileField(blank=True,null=True,upload_to='lead_files/')),('created_at',models.DateTimeField(auto_now_add=True)),('status',models.CharField(choices=[('New','New'),('Qualified','Qualified'),('Meeting','Meeting'),('Proposal','Proposal'),('Negotiation','Negotiation'),('Won','Won'),('Lost','Lost')],default='New',max_length=30)),('notes',models.TextField(blank=True)),('next_follow_up',models.DateField(blank=True,null=True)),('estimated_value',models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True))]),
      migrations.CreateModel(name='Project',fields=[('id',models.BigAutoField(primary_key=True,serialize=False)),('title',models.CharField(max_length=160)),('service',models.CharField(max_length=120)),('description',models.TextField(blank=True)),('status',models.CharField(choices=[(x,x) for x in ['Discovery','Requirements','Development','Testing','Client Review','Deployment','Completed']],default='Discovery',max_length=50)),('progress',models.PositiveIntegerField(default=10)),('next_milestone',models.CharField(blank=True,max_length=180)),('confidential',models.BooleanField(default=False)),('updated_at',models.DateTimeField(auto_now=True)),('client',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name='Milestone',fields=[('id',models.BigAutoField(primary_key=True,serialize=False)),('title',models.CharField(max_length=160)),('due_date',models.DateField(blank=True,null=True)),('completed',models.BooleanField(default=False)),('project',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='milestones',to='agency.project'))]),
      migrations.CreateModel(name='ProjectFile',fields=[('id',models.BigAutoField(primary_key=True,serialize=False)),('title',models.CharField(max_length=160)),('file',models.FileField(upload_to='project_files/')),('uploaded_at',models.DateTimeField(auto_now_add=True)),('project',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='files',to='agency.project'))]),
      migrations.CreateModel(name='SupportTicket',fields=[('id',models.BigAutoField(primary_key=True,serialize=False)),('subject',models.CharField(max_length=180)),('message',models.TextField()),('priority',models.CharField(choices=[('Normal','Normal'),('High','High'),('Urgent','Urgent')],default='Normal',max_length=20)),('status',models.CharField(choices=[('Open','Open'),('In Progress','In Progress'),('Resolved','Resolved')],default='Open',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('client',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL)),('project',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='agency.project'))]),
      migrations.CreateModel(name='Proposal',fields=[('id',models.BigAutoField(primary_key=True,serialize=False)),('title',models.CharField(max_length=180)),('scope',models.TextField()),('deliverables',models.TextField()),('timeline',models.CharField(blank=True,max_length=100)),('price',models.DecimalField(blank=True,decimal_places=2,max_digits=12,null=True)),('terms',models.TextField(blank=True)),('status',models.CharField(choices=[('Draft','Draft'),('Sent','Sent'),('Viewed','Viewed'),('Accepted','Accepted'),('Declined','Declined')],default='Draft',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('lead',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='proposals',to='agency.lead'))]),
    ]
